
name: v0.3

on:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Compile Latex Documents
      id: typeset
      uses: ssinad/typeset-action@v0.3
      with:
        filename: 'hello_world.tex'

    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
          name: artifacts
          path: hello_world.pdf
  upload:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Generated PDF
      uses: actions/download-artifact@v2
      with:
        name: artifacts

    - name: Decrypt large secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        LARGE_FILE_PASSPHRASE: ${{ secrets.LARGE_FILE_PASSPHRASE }}

    - name: Upload to Google Drive
      env:
        FILE_ID: ${{ secrets.FILE_ID }}
      uses: ssinad/gdrive-update-action@v0.3
      with:
        filename: 'hello_world.pdf'
        file_id: ${{ secrets.FILE_ID }}
        key_file: secrets/my_secret.json
